export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_HAS_ERRORED = 'GET_POKEMON_HAS_ERRORED';
export const GET_POKEMON_IS_LOADING = 'GET_POKEMON_IS_LOADING';

export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID';
export const GET_POKEMON_BY_ID_IS_LOADING = 'GET_POKEMON_BY_ID_IS_LOADING';
export const GET_POKEMON_BY_ID_HAS_ERRORED = 'GET_POKEMON_BY_ID_HAS_ERRORED';

export const GET_PAGES_IS_LOADING = 'GET_PAGES_IS_LOADING';
export const GET_PAGES_HAS_ERRORED = 'GET_PAGES_HAS_ERRORED';
export const GET_PAGES_COUNT = 'GET_PAGES_COUNT';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';

export const GET_EVOLUTION_IMG = 'GET_EVOLUTION_IMG';
